# Generated by Django 5.0.3 on 2024-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0009_svgimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgimage',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
