# Generated by Django 5.0.3 on 2024-03-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0004_rename_rectangles_svgimage_svg_code_rectangle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgimage',
            name='svg_code',
        ),
    ]
