# Generated by Django 5.0.3 on 2024-03-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgimage',
            name='svg_code',
        ),
        migrations.AddField(
            model_name='svgimage',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='svgimage',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
