# Generated by Django 5.0.3 on 2024-03-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0006_svgimage_svg_code_delete_rectangle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgimage',
            name='svg_code',
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('color', models.CharField(default='black', max_length=90)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_gallery.svgimage')),
            ],
        ),
    ]
