# Generated by Django 5.0.3 on 2024-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0008_svgimage_editors_alter_rectangle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
